version: '3'
services:
  app:
    container_name: 'app'
    build: 
      context: '.'
    ports:
      - '9696:8080'
    volumes:
      - './app:/app'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'